# $ mint run xcodegen

name: CreateImageClassifier
options:
  bundleIdPrefix: com.akitorahayashi
  deploymentTarget:
    macOS: "15.2"
targets:
  Create Image Classifier:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - target: BinaryClassification
      - target: MultiClassClassification
      - target: MultiLabelClassification
      - target: OvRClassification
      - target: OvOClassification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CreateImageClassifier
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CreateImageClassifierTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: CreateImageClassifierTests
    resources:
      - path: CreateImageClassifierTests/BinaryTests/TestResources
        onDemand: false
      - path: CreateImageClassifierTests/MultiClassTests/TestResources
        onDemand: false
      - path: CreateImageClassifierTests/MultiLabelTests/TestResources
        onDemand: false
      - path: CreateImageClassifierTests/OvRTests/TestResources
        onDemand: false
      - path: CreateImageClassifierTests/OvOTests/TestResources
        onDemand: false
    dependencies:
      - target: BinaryClassification
      - target: MultiClassClassification
      - target: MultiLabelClassification
      - target: OvRClassification
      - target: OvOClassification
      - target: CICFileManager
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CreateImageClassifierTests
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        GENERATE_INFOPLIST_FILE: true
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CICInterface:
    type: framework
    platform: macOS
    sources:
      - path: CICInterface
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CICInterface
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CICConfusionMatrix:
    type: framework
    platform: macOS
    sources:
      - path: CICConfusionMatrix
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CICConfusionMatrix
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CICFileManager:
    type: framework
    platform: macOS
    sources:
      - path: CICFileManager
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CICFileManager
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  CICTrainingResult:
    type: framework
    platform: macOS
    sources:
      - path: CICTrainingResult
    dependencies:
      - target: CICInterface
      - target: CICConfusionMatrix
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CICTrainingResult
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  BinaryClassification:
    type: framework
    platform: macOS
    sources:
      - path: BinaryClassification/BinarySources
    resources:
      - path: BinaryClassification/Resources
    dependencies:
      - target: CICInterface
      - target: CICConfusionMatrix
      - target: CICFileManager
      - target: CICTrainingResult
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.BinaryClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  MultiClassClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiClassClassification/MultiClassSources
    resources:
      - path: MultiClassClassification/Resources
    dependencies:
      - target: CICInterface
      - target: CICConfusionMatrix
      - target: CICFileManager
      - target: CICTrainingResult
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiClassClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  MultiLabelClassification:
    type: framework
    platform: macOS
    sources:
      - path: MultiLabelClassification/MultiLabelSources
    resources:
      - path: MultiLabelClassification/Resources
    dependencies:
      - target: CICInterface
      - target: CICConfusionMatrix
      - target: CICFileManager
      - target: CICTrainingResult
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.MultiLabelClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        DEFINES_MODULE: "YES"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvRClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvRClassification/OvRSources
    resources:
      - path: OvRClassification/Resources
    dependencies:
      - target: CICInterface
      - target: CICConfusionMatrix
      - target: CICFileManager
      - target: CICTrainingResult
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvRClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO

  OvOClassification:
    type: framework
    platform: macOS
    sources:
      - path: OvOClassification/OvOSources
    resources:
      - path: OvOClassification/Resources
    dependencies:
      - target: CICInterface
      - target: CICConfusionMatrix
      - target: CICFileManager
      - target: CICTrainingResult
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.OvOClassification
        MACOSX_DEPLOYMENT_TARGET: "15.2"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
