# $ mint run xcodegen generate

name: CreateImageClassifier
options:
  deploymentTarget:
    macOS: "15.2"
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    COREML_CODEGEN_LANGUAGE: Swift
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

packages:
  CreateImageClassifier:
    path: .
    products:
      - CICInterface
      - CICConfusionMatrix
      - CICFileManager
      - CICTrainingResult
      - BinaryClassifier
      - MultiClassClassifier
      - OvOClassifier
      - OvRClassifier

targets:
  CreateImageClassifier:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - package: CreateImageClassifier
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CreateImageClassifier
        MACOSX_DEPLOYMENT_TARGET: "15.2"

  CICConfusionMatrixTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: CICConfusionMatrix/Tests
    dependencies:
      - package: CreateImageClassifier
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CICConfusionMatrixTests
        GENERATE_INFOPLIST_FILE: YES

  CICFileManagerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: CICFileManager/Tests
    dependencies:
      - package: CreateImageClassifier
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CICFileManagerTests
        GENERATE_INFOPLIST_FILE: YES

  ClassifierTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Classifiers/Tests
    dependencies:
      - package: CreateImageClassifier
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.ClassifierTests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  CreateImageClassifier:
    build:
      targets:
        CreateImageClassifier: all
        CICConfusionMatrixTests: all
        CICFileManagerTests: all
        ClassifierTests: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - CICConfusionMatrixTests
        - CICFileManagerTests
        - ClassifierTests
      targets:
        - CICConfusionMatrixTests
        - CICFileManagerTests
        - ClassifierTests
