# $ mint run xcodegen generate

name: CreateImageClassifier
options:
  deploymentTarget:
    macOS: "15.2"
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 1
    COREML_CODEGEN_LANGUAGE: Swift
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

packages:
  CreateImageClassifier:
    path: .

targets:
  CreateImageClassifier:
    type: tool
    platform: macOS
    sources:
      - path: main.swift
    dependencies:
      - package: CreateImageClassifier
        product: CreateImageClassifier
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akitorahayashi.CreateImageClassifier
        MACOSX_DEPLOYMENT_TARGET: "15.2"

schemes:
  CreateImageClassifier:
    build:
      targets:
        CreateImageClassifier: all
    run:
      config: Debug
